### ISSUE TITLE
多图上传出现错误

### ISSUE THREAD

**Issue by baizhiqiang** [qiniudemo/weixin-app-upload#1]
当多图上传时不应该用for循环，因为for循环很快执行完，但是文件上传是个比较慢的过程，应该在wx.uploadFile()的complete中判断是否已经上传完，为否时再次调用本方法。参考http://www.jb51.net/article/115618.htm

**Comment by jemygraw** [comment]
for循环只是个例子，可以使用callback的方式上传多个图。
